# Generated by Django 4.1.4 on 2023-01-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('kanji_classification', models.CharField(max_length=200)),
                ('radical', models.CharField(max_length=200)),
                ('joyo_reading', models.CharField(max_length=200)),
                ('non_joyo_reading', models.CharField(max_length=200)),
                ('meaning', models.CharField(max_length=200)),
                ('on_within_joyo', models.CharField(max_length=200)),
                ('kun_within_joyo', models.CharField(max_length=200)),
            ],
        ),
    ]
