# Generated by Django 4.1.4 on 2023-01-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjinator', '0002_alter_kanji_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='JLPT',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanji',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanji',
            name='strokes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
