# Generated by Django 4.1.4 on 2023-01-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjinator', '0004_alter_kanji_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='non_joyo_reading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
