# Generated by Django 4.1.4 on 2023-01-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjinator', '0005_alter_kanji_non_joyo_reading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanji',
            old_name='symbol',
            new_name='kanji',
        ),
        migrations.RenameField(
            model_name='kanji',
            old_name='non_joyo_reading',
            new_name='kun_readings',
        ),
        migrations.RenameField(
            model_name='kanji',
            old_name='joyo_reading',
            new_name='meanings',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='kun_within_joyo',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='on_within_joyo',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='radical',
        ),
        migrations.AddField(
            model_name='kanji',
            name='name_readings',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kanji',
            name='on_readings',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='JLPT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='kanji_classification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
